apiVersion: v1
kind: Pod
metadata:
  labels:
    app: shop
  name: shop-frontend
spec:
  containers:
    - name: shop-api
      image: eu.gcr.io/ceremonial-rush-190313/shop:latest
      env:
      - name: DB_HOST
        value: mysql
      - name: DB_NAME
        value: shop
      - name: DB_PASS
        value: shop
      - name: DB_USER
        value: shop
      - name: FLASK_APP
        value: /app/service/__init__.py
      - name: FLASK_DEBUG
        value: "1"
      ports:
        - containerPort: 8000
