"""added blacklisted jwt table

Revision ID: 2d8c382be900
Revises: c7bb253b73f0
Create Date: 2017-12-26 11:29:56.795286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8c382be900'
down_revision = 'c7bb253b73f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedJWT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklistedJWT')
    # ### end Alembic commands ###
