"""Added password field to user table

Revision ID: c7bb253b73f0
Revises: 596b4cce457f
Create Date: 2017-12-24 20:58:21.027187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bb253b73f0'
down_revision = '596b4cce457f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=False))
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
